spring:
  rabbitmq:
    host: 127.0.0.1 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: admin # 用户名
    password: admin # 密码
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS