spring:
  datasource: #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db
    username: root
    password: root
  main:
    banner-mode: off #关闭SpringBoot启动图标

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志
  global-config:
      banner: off #关闭mybatis启动图标
      db-config:
#        id-type: assign_id #全局主键id生成策略
        table-prefix: tbl_ #数据库表名前缀
        # 逻辑删除名字段
        logic-delete-field: deleted
        # 逻辑删除字面值：未删除0
        logic-not-delete-value: 0
        # 逻辑删除字面值：已删除1
        logic-delete-value: 1


