server:
  port: 81

spring:
  boot:
    admin:
      client:
        url: http://localhost:80 #监控平台的地址
management:
  endpoint:
    health:
      show-details: always #显示健康信息
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" #开放全部信息
    enabled-by-default: true #是否开放默认端点

info:
  appName: "admin_client"
#  version: @project.version@
#  companyName: @project.company@
